language: csharp
mono: none
dotnet: 2.2
dist: xenial
install:
- dotnet restore
script:
- dotnet build
- dotnet test WebClient.UnitTest/WebClient.UnitTest.csproj
- dotnet test DataSearchContain.UnitTest/DataSearchContain.UnitTest.csproj